LANGUAGE = {"NL": {"GAMEOVER": "Je hebt je sollicitatie gemist!",
                   "DEAD1": "Guido heeft al zijn motivatie verloren...",
                   "DEAD2": "Hij is niet langer in staat om naar zijn sollicitatie te gaan!",
                   "RESTARTKEY": "Druk op enter om opnieuw te spelen",
                   "STARTKEY": "Druk op enter om te beginnen",
                   "CONTROLKEY": "Druk op 'C' voor de besturing",
                   "ESCKEY": "Druk op 'Esc' om af te sluiten",
                   "LANGUAGEKEY": "Druk op 'L' om de taal te veranderen",
                   "TITLE": "Guido's CV - Het Spel",
                   "CVPARTS": "CV onderdelen: ",
                   "TIMEBOOSTS": "Tijd power-ups: ",
                   "SPEEDBOOSTS": "Snelheid power-ups: ",
                   "SCORE": "Eindscore: ",
                   "TIME": "Resterende Tijd: ",
                   "PAUSE": "Gepauseerd",
                   "YOUHAVE": "Je hebt gevonden:",
                   "CONTACT": "Contact informatie:",
                   "THANKS": "Bedankt voor het spelen :)",
                   "ALLCV": "Alle CV Onderdelen!!",
                   "HIREME": "Neem mij a.u.b aan ;)",
                   "COLLECTED": "Verzamelde CV onderdelen"
                   },
            "EN": {"GAMEOVER": "You have missed your application!",
                   "DEAD1": "Guido has lost all his motivation...",
                   "DEAD2": "He is no longer able to go to the job application!",
                   "RESTARTKEY": "Press enter to start again",
                   "STARTKEY": "Press enter to start",
                   "CONTROLKEY": "Press 'C' for controls",
                   "ESCKEY": "Press 'Esc' to exit the game",
                   "LANGUAGEKEY": "Press 'L' to change language",
                   "TITLE": "Guido's CV - The Game",
                   "CVPARTS": "CV parts: ",
                   "TIMEBOOSTS": "Time power-ups: ",
                   "SPEEDBOOSTS": "Speed power-ups: ",
                   "SCORE": "Final score: ",
                   "TIME": "Time left: ",
                   "PAUSE": "Paused",
                   "YOUHAVE": "You have found:",
                   "CONTACT": "Contact information:",
                   "THANKS": "Thanks for playing :)",
                   "ALLCV": "All CV parts!!",
                   "HIREME": "Hire me please ;)",
                   "COLLECTED": "Collected CV parts"
                   }
            }

NPCLANGUAGE = {
    "NL": {"BOSS": ["Hallo daar Guido, je bent keurig op tijd voor je gesprek.", "Laten we eens kijken naar je CV."],
           "MOM": ["Hoi Guido, veel succes met je sollicitatie vandaag!", "Vergeet je CV niet!",
                   "Volgens mij zie ik daar een deel op de TV liggen."],
           "DAD": ["Ik ben druk bezig met de afwas.",
                   "Kan jij even de borden checken?", "Er mag niks tussen zitten wat niet nat mag worden."],
           "LADY": ["Hoi, wat een mooie dag om door de stad te lopen he?",
                    "Ik vraag mij af wat er in de grote kist achter mij zit..."],
           "LADY2": ["Hoi, ik zag je net oversteken, wel oppassen voor de auto's he!"],
           "LADY_PONYTAIL": ["Ik heb net lekker door het bos gewandeld.",
                             "Ik zag iets wat op een CV leek tegen 1 van de bomen aan gewaaid zitten.",
                             "Hopelijk is niemand dat CV kwijt."],
           "WORKER1": ["Hallo daar, welkom bij 'Fantastisch bedrijf BV'.", "De baas is in zijn kantoor."],
           "WORKER2": ["Hallo, jij bent vast de persoon die komt solliciteren.", "Veel succes!"],
           "WORKER3": ["Hey daar!", "Zorg wel dat je een volledig CV bij je hebt om aan de baas te laten zien."],
           "WORKER4": ["Ik kan altijd eeuwen naar de vissen kijken in een aquarium.", "Zo ontspannend.",
                       "Hmm. Ligt er nou iets bovenop het aquarium?"],
           "POLICE": ["Goedendag.", "Onthoud dat zwemmen in de vijver is verboden."],
           "POLICE2": ["Ik houd toezicht op de wedstrijd.", "Gelukkig verloopt deze vriendelijk."],
           "POLICE3": ["Als je hier te lang geparkeerd staat krijg je een bekeuring."],
           "BALDGUY": ["Er zit iets onder deze steen.", "Maar ik wil niet kijken wat het is.",
                       "Wat als het een gevaarlijk dier is?"],
           "CASHIER1": ["Welkom bij de 'Mega Markt'!", "De beste supermarkt in de stad.",
                        "(Tevens de enige supermarkt...)"],
           "CASHIER2": ["U zoekt een verloren CV?", "Ik zag wel iets vreemds liggen in rek 2."],
           "CASHIER3": ["Er is gloednieuwe voorraad!", "Het ligt op de gevulde plank het dicht bij deze kassa."],
           "FOOTBALLPLAYER1": ["Hey, geen fans op het speelveld!"],
           "FOOTBALLPLAYER2": ["We staan 0-1 achter.", "Ik werd geraakt door een stukje papier.",
                               "Dat was het moment waarop de tegenstander heeft gescoord.",
                               "Ik heb het stuk papier in 1 van de vuilnisbakken gegooid."],
           "FOOTBALLPLAYER3": ["Hup team groen!"],
           "FOOTBALLPLAYER4": ["Het blauwe team is het beste!"],
           "GUY1": ["He bah, ik heb een parkeerboete.", "Oh wacht, dit is geen boete.", "Dit lijkt wel een CV."],
           "GUY2": ["Lekker weer vandaag he?"],
           "GUY3": ["Hey, gezellig dat je even een praatje komt maken.", "Ik raad je aan met iedereen te praten.",
                    "Je weet maar nooit wat iemand te vertellen heeft."],
           "EASTEREGG": ["Hey, je bent helemaal in de hoek van de map!", "Ik ben Dhr. E. A. Steregg",
                         "Heel erg bedankt voor het spelen van dit CV spel!",
                         "Heb je al 10 CV delen?", "Zo niet, klik dan eens op dit plantje naast mij."]
           },
    "EN": {"BOSS": ["Hello there Guido, you are perfectly on time.", "Let's take a look at your CV."],
           "MOM": ["Hi Guido, good luck with your application today!", "Don't forget your CV!", "I think i see a "
                                                                                                "piece of it lying on "
                                                                                                "the TV."],
           "DAD": ["I'm doing the dishes.",
                   "Can you check the plates?",
                   "Make sure there is nothing between them that is not supposed to get wet."],
           "LADY": ["Hi there, nice day for a stroll through the city right?",
                    "I wonder what's in that big box behind me..."],
           "LADY2": ["Hey there, i just saw you crossing the street, remember to be mindful of cars!"],
           "LADY_PONYTAIL": ["I just had a nice stroll through the woods.",
                             "I saw something resembling a CV sticking to 1 of the trees.",
                             "I sure hope nobody lost that piece of CV."],
           "WORKER1": ["Hello there, welcome to 'Awesome Company Inc.' The boss is in his office."],
           "WORKER2": ["Hello, you must be here for the application.", "Good luck!"],
           "WORKER3": ["Hey there!", "Make sure to have your complete CV with you to show to the boss."],
           "WORKER4": ["I can watch the fish in an aquarium forever.", "It's so relaxing.",
                       "Hmm. Is there something lying on top of the tank?"],
           "POLICE": ["Greetings.", "Remember that swimming is the pond is prohibited."],
           "POLICE2": ["I am keeping a close eye on the game.", "Luckily everything seems to go friendly."],
           "POLICE3": ["If you are parked here for too long, you get a ticket."],
           "BALDGUY": ["There is something under this rock.", "But i dont want to take a look.",
                       "What if it is a dangerous animal?"],
           "CASHIER1": ["Welcome to 'Mega Market'!", "The best supermarket in town.", "(Also the only "
                                                                                      "supermarket...)"],
           "CASHIER2": ["You are looking for a lost CV?", "I did see something strange laying in rack 2."],
           "CASHIER3": ["We have a brand new stock!", "You can find it on the stocked shelf nearest to this register."],
           "FOOTBALLPLAYER1": ["Hey, no fans allowed on the field!"],
           "FOOTBALLPLAYER2": ["We are behind 0-1.", "I got hit by a piece of paper.", "That's when the enemy scored.",
                               "I threw the paper in one of the trashcans."],
           "FOOTBALLPLAYER3": ["Go team green!"],
           "FOOTBALLPLAYER4": ["Blue team rules!"],
           "GUY1": ["Aww shucks, i have parking ticket.", "Oh wait, this is not a ticket.", "This looks like a CV."],
           "GUY2": ["Today is a beautiful day isn't it?"],
           "GUY3": ["Hey, how nice of you to come have a chat with me.",
                    "I suggest that you speak with everyone you meet.",
                    "You will never know what someone has say."],
           "EASTEREGG": ["Hey, you made it all the way to the edge of the map!", "I am Mr. E. A. Steregg",
                         "Thank you so much for playing this CV game!",
                         "Have you collected 10 CV parts yet?",
                         "If not, may i suggest checking out this plant next to me."]
           }
}
